package com.securevault.websecurevault.Utilities;

public class ColumnNames {
    //Names of the record columns
    public static final String title = "title";
    public static final String category = "category";
    public static final String userName = "user_name";
    public static final String password = "password";
    public static final String accountNumber = "account_number";
    public static final String bankNumber = "bank_number";
    public static final String bankAddress = "bank_address";
    public static final String note = "note";
    public static final String cardNumber = "card_number";
    public static final String cvv = "cvv";
    public static final String cardExpiringDate = "expiring_date";
    public static final String website = "website";
    public static final String email = "email";
    public static final String recordId = "record_id";  //AutoGenerated
    public static final String userId = "user_id"; //For both tables (Records and Users)
    //Names of the users columns
    public static final String firstName = "first_name";
    public static final String lastName = "last_name";
    public static final String masterPass = "master_pass";

    public ColumnNames() {
    }
}
